### ISSUE TITLE
Is there any native layer at all?

### ISSUE THREAD

**Issue by tomcam** [Jasonette/Jasonette-Web#4]
Love Jasonette from afar, and this looks awesome. I have always assumed that with stock Jasonette to get access to the UI controls, camera, etc. there was some kind of native-to-javascript bridge runtime component. Am I wrong? I must be because if this is call Javascript I assume there never was to begin with.

**Comment by gliechtenstein** [comment]
Thanks, could you share where you got the idea that Jasonette are using JavaScript? If there's anywhere on the website that may be misleading I would like to correct them so that there's no misunderstanding.

Both Jasonette-iOS and Jasonette-Android are native projects. Jasonette-iOS is written in Objective-C, and Jasonette-Android is written in Java. That's the whole point. 

There's no JavaScript to Native binding. The only "binding" that happens is directly from JSON to native. The native components directly interpret the JSON markup into native functions and run them.

The only place we use JavaScript is for complex JSON template parsing, because Jasonette requires extreme flexibility in parsing and transforming all kinds of JSON objects. And since the "native language" of JSON is JavaScript (JSON = JavaScript Object Notation), it's actually much more efficient to use JavaScript to take care of this part. That's why I wrote this specific part in JavaScript https://selecttransform.github.io/site/

But other than that, most of the app is completely native.

As for Jasonette-Web, this is a project to build a web implementation of the protocol so it can be used in a browser or similar settings. Hope this makes sense.

**Comment by tomcam** [comment]
BRAIN FART! That's where I got the idea. The docs are super clear about doing this from JSON. Thanks for the clarification, which I really shouldn't have needed :( 

It all made perfect sense.
